apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hotel-management.fullname" . }}
  labels:
    {{- include "hotel-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ include "hotel-management.appKey" . | quote }}
  {{- if not .Values.database.existingSecret }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
  MAIL_PASSWORD: {{ .Values.mail.password | quote }}
